name = "airbus"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-11-28"

[assets]
directory = "./public"

[[rules]]
type = "Text"
globs = ["**/*.yaml"]
fallthrough = true

[vars]
DIRECT_DOMAINS = "medowo.net"

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "f1e93a5d-7d09-43b1-ad29-d478c37feb5a"
